{{- if .Values.vault.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vault
  namespace: secrets
  labels:
    {{- include "hc-secrets.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
    {{- if .Values.tls.enabled }} - websecure {{- end }}
  routes:
    - match: Host(`{{ include "hc-secrets.fqdn" (dict "host" .Values.vault.host "domain" .Values.domain) }}`)
      kind: Rule
      services:
        - name: vault
          port: {{ .Values.vault.port }}
  {{- if .Values.tls.enabled }}
  tls:
    certResolver: {{ .Values.tls.certResolver }}
    domains:
      - main: {{ .Values.domain }}
        sans: ["*.{{ .Values.domain }}"]
  {{- end }}
{{- end }}
