tunnel: <YOUR_TUNNEL_ID>
credentials-file: /etc/cloudflared/<tunnel-id>.json

ingress:
  - hostname: hello.mycloud.com
    service: http://traefik.kube-system.svc.cluster.local:80
  - hostname: api.mycloud.com
    service: http://traefik.kube-system.svc.cluster.local:80
  - hostname: storage.mycloud.com
    service: http://traefik.kube-system.svc.cluster.local:80
  - hostname: auth.mycloud.com
    service: http://traefik.kube-system.svc.cluster.local:80
  - service: http_status:404