{{- if eq .Values.mode "cloudflare" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
  labels:
    {{- include "hc.labels" . | nindent 4 }}
data:
  config.yml: |
    tunnel: {{ .Values.cloudflare.tunnelId }}
    credentials-file: /etc/cloudflared/credentials.json
    ingress:
      - hostname: {{ include "hc.fqdn" (dict "host" (default "hello" (index .Values "demoApp" "host")) "domain" .Values.domain) }}
        service: http://traefik.kube-system.svc.cluster.local:80
      - service: http_status:404
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared
  labels:
    {{- include "hc.labels" . | nindent 4 }}
{{- end }}
